version: 2

project_name: go-sea

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: gsea
    main: .
    binary: go-sea
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/borland502/go-sea/internal/version.Version={{.Version}}
      - -X github.com/borland502/go-sea/internal/version.Commit={{.Commit}}
      - -X github.com/borland502/go-sea/internal/version.Date={{.Date}}

checksum:
  name_template: checksums.txt

archives:
  - id: tarball
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - configs/go-sea.toml
  - id: zipball
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - configs/go-sea.toml

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"
  footer: |
    Maintained by Jeremy Hettenhouser <jhettenh@gmail.com>.
