package appconfig

import (
	"strings"
	"testing"
)

func TestRenderIncludesExpectedSections(t *testing.T) {
	text := Render(Default(), "go-sea")

	mustContain := []string{
		"# Generated by go-sea init-config.",
		"[example]",
		"[output]",
		"[palette]",
		"favorite_tide = \"rising tide\"",
		"show_paths = true",
		"purple = \"#948ae3\"",
	}

	for _, expected := range mustContain {
		if !strings.Contains(text, expected) {
			t.Fatalf("rendered config missing %q", expected)
		}
	}
}
