package appconfig

import (
	"fmt"
	"strings"
)

const (
	paletteSourceURL = "https://github.com/borland502/nix-config/blob/main/home-manager/config/colors/monokai.base24.yaml"
)

type Config struct {
	Example ExampleConfig `mapstructure:"example"`
	Output  OutputConfig  `mapstructure:"output"`
	Palette PaletteConfig `mapstructure:"palette"`
}

type ExampleConfig struct {
	Greeting     string `mapstructure:"greeting"`
	Name         string `mapstructure:"name"`
	Location     string `mapstructure:"location"`
	FavoriteTide string `mapstructure:"favorite_tide"`
}

type OutputConfig struct {
	Color     bool `mapstructure:"color"`
	ShowPaths bool `mapstructure:"show_paths"`
}

type PaletteConfig struct {
	Black  string `mapstructure:"black"`
	Gray   string `mapstructure:"gray"`
	White  string `mapstructure:"white"`
	Pink   string `mapstructure:"pink"`
	Orange string `mapstructure:"orange"`
	Yellow string `mapstructure:"yellow"`
	Green  string `mapstructure:"green"`
	Cyan   string `mapstructure:"cyan"`
	Purple string `mapstructure:"purple"`
}

type PaletteEntry struct {
	Key string
	Hex string
}

func (palette PaletteConfig) Entries() []PaletteEntry {
	return []PaletteEntry{
		{Key: "black", Hex: palette.Black},
		{Key: "gray", Hex: palette.Gray},
		{Key: "white", Hex: palette.White},
		{Key: "pink", Hex: palette.Pink},
		{Key: "orange", Hex: palette.Orange},
		{Key: "yellow", Hex: palette.Yellow},
		{Key: "green", Hex: palette.Green},
		{Key: "cyan", Hex: palette.Cyan},
		{Key: "purple", Hex: palette.Purple},
	}
}

func Default() Config {
	return Config{
		Example: ExampleConfig{
			Greeting:     "Ahoy",
			Name:         "Captain",
			Location:     "Pacific Ocean",
			FavoriteTide: "rising tide",
		},
		Output: OutputConfig{
			Color:     true,
			ShowPaths: true,
		},
		Palette: defaultPalette(),
	}
}

func defaultPalette() PaletteConfig {
	return PaletteConfig{
		Black:  "#222222",
		Gray:   "#69676c",
		White:  "#f7f1ff",
		Pink:   "#FC618D",
		Orange: "#fd9353",
		Yellow: "#FCE566",
		Green:  "#7BD88F",
		Cyan:   "#5AD4E6",
		Purple: "#948ae3",
	}
}

func Render(config Config, binaryName string) string {
	var builder strings.Builder

	fmt.Fprintf(&builder, "# Generated by %s init-config.\n", binaryName)
	builder.WriteString("#\n")
	builder.WriteString("# Run the example program with:\n")
	fmt.Fprintf(&builder, "#   %s example\n", binaryName)
	builder.WriteString("#\n")
	builder.WriteString("# Override any value with environment variables like:\n")
	builder.WriteString("#   GSEA_EXAMPLE_NAME=\"Harbor Team\"\n")
	builder.WriteString("#   GSEA_OUTPUT_SHOW_PATHS=false\n")
	builder.WriteString("#   GSEA_PALETTE_PURPLE=\"#948AE3\"\n")
	builder.WriteString("#\n")
	builder.WriteString("# Curated palette subset: one black, one gray, one white, and six accents.\n")
	fmt.Fprintf(&builder, "# Palette source: %s\n\n", paletteSourceURL)

	builder.WriteString("[example]\n")
	fmt.Fprintf(&builder, "greeting = %q\n", config.Example.Greeting)
	fmt.Fprintf(&builder, "name = %q\n", config.Example.Name)
	fmt.Fprintf(&builder, "location = %q\n", config.Example.Location)
	fmt.Fprintf(&builder, "favorite_tide = %q\n\n", config.Example.FavoriteTide)

	builder.WriteString("[output]\n")
	fmt.Fprintf(&builder, "color = %t\n", config.Output.Color)
	fmt.Fprintf(&builder, "show_paths = %t\n\n", config.Output.ShowPaths)

	builder.WriteString("[palette]\n")
	for _, entry := range config.Palette.Entries() {
		fmt.Fprintf(&builder, "%s = %q\n", entry.Key, entry.Hex)
	}

	return builder.String()
}
